// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/grpc/proto/mayhem.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/hivemachine/internal/grpc/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MayhemServiceName is the fully-qualified name of the MayhemService service.
	MayhemServiceName = "mayhem.v1.MayhemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MayhemServiceListModelsProcedure is the fully-qualified name of the MayhemService's ListModels
	// RPC.
	MayhemServiceListModelsProcedure = "/mayhem.v1.MayhemService/ListModels"
	// MayhemServiceChatCompletionsProcedure is the fully-qualified name of the MayhemService's
	// ChatCompletions RPC.
	MayhemServiceChatCompletionsProcedure = "/mayhem.v1.MayhemService/ChatCompletions"
	// MayhemServiceCompletionsProcedure is the fully-qualified name of the MayhemService's Completions
	// RPC.
	MayhemServiceCompletionsProcedure = "/mayhem.v1.MayhemService/Completions"
	// MayhemServiceStreamCompletionsProcedure is the fully-qualified name of the MayhemService's
	// StreamCompletions RPC.
	MayhemServiceStreamCompletionsProcedure = "/mayhem.v1.MayhemService/StreamCompletions"
	// MayhemServiceStreamChatCompletionsProcedure is the fully-qualified name of the MayhemService's
	// StreamChatCompletions RPC.
	MayhemServiceStreamChatCompletionsProcedure = "/mayhem.v1.MayhemService/StreamChatCompletions"
	// MayhemServiceListProvidersProcedure is the fully-qualified name of the MayhemService's
	// ListProviders RPC.
	MayhemServiceListProvidersProcedure = "/mayhem.v1.MayhemService/ListProviders"
)

// MayhemServiceClient is a client for the mayhem.v1.MayhemService service.
type MayhemServiceClient interface {
	// ListModels returns all models available from the Rust core.
	ListModels(context.Context, *connect.Request[pb.ListModelsRequest]) (*connect.Response[pb.ListModelsResponse], error)
	// ChatCompletions handles chat-based inference (unary).
	ChatCompletions(context.Context, *connect.Request[pb.ChatCompletionRequest]) (*connect.Response[pb.ChatCompletionResponse], error)
	// Completions handles text completion (unary).
	Completions(context.Context, *connect.Request[pb.CompletionRequest]) (*connect.Response[pb.CompletionResponse], error)
	// StreamCompletions streams text completion chunks.
	StreamCompletions(context.Context, *connect.Request[pb.CompletionRequest]) (*connect.ServerStreamForClient[pb.StreamChunk], error)
	// StreamChatCompletions streams chat completion chunks.
	StreamChatCompletions(context.Context, *connect.Request[pb.ChatCompletionRequest]) (*connect.ServerStreamForClient[pb.StreamChunk], error)
	// ListProviders returns active providers from the Rust core.
	ListProviders(context.Context, *connect.Request[pb.ListProvidersRequest]) (*connect.Response[pb.ListProvidersResponse], error)
}

// NewMayhemServiceClient constructs a client for the mayhem.v1.MayhemService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMayhemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MayhemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mayhemServiceMethods := pb.File_internal_grpc_proto_mayhem_proto.Services().ByName("MayhemService").Methods()
	return &mayhemServiceClient{
		listModels: connect.NewClient[pb.ListModelsRequest, pb.ListModelsResponse](
			httpClient,
			baseURL+MayhemServiceListModelsProcedure,
			connect.WithSchema(mayhemServiceMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		chatCompletions: connect.NewClient[pb.ChatCompletionRequest, pb.ChatCompletionResponse](
			httpClient,
			baseURL+MayhemServiceChatCompletionsProcedure,
			connect.WithSchema(mayhemServiceMethods.ByName("ChatCompletions")),
			connect.WithClientOptions(opts...),
		),
		completions: connect.NewClient[pb.CompletionRequest, pb.CompletionResponse](
			httpClient,
			baseURL+MayhemServiceCompletionsProcedure,
			connect.WithSchema(mayhemServiceMethods.ByName("Completions")),
			connect.WithClientOptions(opts...),
		),
		streamCompletions: connect.NewClient[pb.CompletionRequest, pb.StreamChunk](
			httpClient,
			baseURL+MayhemServiceStreamCompletionsProcedure,
			connect.WithSchema(mayhemServiceMethods.ByName("StreamCompletions")),
			connect.WithClientOptions(opts...),
		),
		streamChatCompletions: connect.NewClient[pb.ChatCompletionRequest, pb.StreamChunk](
			httpClient,
			baseURL+MayhemServiceStreamChatCompletionsProcedure,
			connect.WithSchema(mayhemServiceMethods.ByName("StreamChatCompletions")),
			connect.WithClientOptions(opts...),
		),
		listProviders: connect.NewClient[pb.ListProvidersRequest, pb.ListProvidersResponse](
			httpClient,
			baseURL+MayhemServiceListProvidersProcedure,
			connect.WithSchema(mayhemServiceMethods.ByName("ListProviders")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mayhemServiceClient implements MayhemServiceClient.
type mayhemServiceClient struct {
	listModels            *connect.Client[pb.ListModelsRequest, pb.ListModelsResponse]
	chatCompletions       *connect.Client[pb.ChatCompletionRequest, pb.ChatCompletionResponse]
	completions           *connect.Client[pb.CompletionRequest, pb.CompletionResponse]
	streamCompletions     *connect.Client[pb.CompletionRequest, pb.StreamChunk]
	streamChatCompletions *connect.Client[pb.ChatCompletionRequest, pb.StreamChunk]
	listProviders         *connect.Client[pb.ListProvidersRequest, pb.ListProvidersResponse]
}

// ListModels calls mayhem.v1.MayhemService.ListModels.
func (c *mayhemServiceClient) ListModels(ctx context.Context, req *connect.Request[pb.ListModelsRequest]) (*connect.Response[pb.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// ChatCompletions calls mayhem.v1.MayhemService.ChatCompletions.
func (c *mayhemServiceClient) ChatCompletions(ctx context.Context, req *connect.Request[pb.ChatCompletionRequest]) (*connect.Response[pb.ChatCompletionResponse], error) {
	return c.chatCompletions.CallUnary(ctx, req)
}

// Completions calls mayhem.v1.MayhemService.Completions.
func (c *mayhemServiceClient) Completions(ctx context.Context, req *connect.Request[pb.CompletionRequest]) (*connect.Response[pb.CompletionResponse], error) {
	return c.completions.CallUnary(ctx, req)
}

// StreamCompletions calls mayhem.v1.MayhemService.StreamCompletions.
func (c *mayhemServiceClient) StreamCompletions(ctx context.Context, req *connect.Request[pb.CompletionRequest]) (*connect.ServerStreamForClient[pb.StreamChunk], error) {
	return c.streamCompletions.CallServerStream(ctx, req)
}

// StreamChatCompletions calls mayhem.v1.MayhemService.StreamChatCompletions.
func (c *mayhemServiceClient) StreamChatCompletions(ctx context.Context, req *connect.Request[pb.ChatCompletionRequest]) (*connect.ServerStreamForClient[pb.StreamChunk], error) {
	return c.streamChatCompletions.CallServerStream(ctx, req)
}

// ListProviders calls mayhem.v1.MayhemService.ListProviders.
func (c *mayhemServiceClient) ListProviders(ctx context.Context, req *connect.Request[pb.ListProvidersRequest]) (*connect.Response[pb.ListProvidersResponse], error) {
	return c.listProviders.CallUnary(ctx, req)
}

// MayhemServiceHandler is an implementation of the mayhem.v1.MayhemService service.
type MayhemServiceHandler interface {
	// ListModels returns all models available from the Rust core.
	ListModels(context.Context, *connect.Request[pb.ListModelsRequest]) (*connect.Response[pb.ListModelsResponse], error)
	// ChatCompletions handles chat-based inference (unary).
	ChatCompletions(context.Context, *connect.Request[pb.ChatCompletionRequest]) (*connect.Response[pb.ChatCompletionResponse], error)
	// Completions handles text completion (unary).
	Completions(context.Context, *connect.Request[pb.CompletionRequest]) (*connect.Response[pb.CompletionResponse], error)
	// StreamCompletions streams text completion chunks.
	StreamCompletions(context.Context, *connect.Request[pb.CompletionRequest], *connect.ServerStream[pb.StreamChunk]) error
	// StreamChatCompletions streams chat completion chunks.
	StreamChatCompletions(context.Context, *connect.Request[pb.ChatCompletionRequest], *connect.ServerStream[pb.StreamChunk]) error
	// ListProviders returns active providers from the Rust core.
	ListProviders(context.Context, *connect.Request[pb.ListProvidersRequest]) (*connect.Response[pb.ListProvidersResponse], error)
}

// NewMayhemServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMayhemServiceHandler(svc MayhemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mayhemServiceMethods := pb.File_internal_grpc_proto_mayhem_proto.Services().ByName("MayhemService").Methods()
	mayhemServiceListModelsHandler := connect.NewUnaryHandler(
		MayhemServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(mayhemServiceMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	mayhemServiceChatCompletionsHandler := connect.NewUnaryHandler(
		MayhemServiceChatCompletionsProcedure,
		svc.ChatCompletions,
		connect.WithSchema(mayhemServiceMethods.ByName("ChatCompletions")),
		connect.WithHandlerOptions(opts...),
	)
	mayhemServiceCompletionsHandler := connect.NewUnaryHandler(
		MayhemServiceCompletionsProcedure,
		svc.Completions,
		connect.WithSchema(mayhemServiceMethods.ByName("Completions")),
		connect.WithHandlerOptions(opts...),
	)
	mayhemServiceStreamCompletionsHandler := connect.NewServerStreamHandler(
		MayhemServiceStreamCompletionsProcedure,
		svc.StreamCompletions,
		connect.WithSchema(mayhemServiceMethods.ByName("StreamCompletions")),
		connect.WithHandlerOptions(opts...),
	)
	mayhemServiceStreamChatCompletionsHandler := connect.NewServerStreamHandler(
		MayhemServiceStreamChatCompletionsProcedure,
		svc.StreamChatCompletions,
		connect.WithSchema(mayhemServiceMethods.ByName("StreamChatCompletions")),
		connect.WithHandlerOptions(opts...),
	)
	mayhemServiceListProvidersHandler := connect.NewUnaryHandler(
		MayhemServiceListProvidersProcedure,
		svc.ListProviders,
		connect.WithSchema(mayhemServiceMethods.ByName("ListProviders")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mayhem.v1.MayhemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MayhemServiceListModelsProcedure:
			mayhemServiceListModelsHandler.ServeHTTP(w, r)
		case MayhemServiceChatCompletionsProcedure:
			mayhemServiceChatCompletionsHandler.ServeHTTP(w, r)
		case MayhemServiceCompletionsProcedure:
			mayhemServiceCompletionsHandler.ServeHTTP(w, r)
		case MayhemServiceStreamCompletionsProcedure:
			mayhemServiceStreamCompletionsHandler.ServeHTTP(w, r)
		case MayhemServiceStreamChatCompletionsProcedure:
			mayhemServiceStreamChatCompletionsHandler.ServeHTTP(w, r)
		case MayhemServiceListProvidersProcedure:
			mayhemServiceListProvidersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMayhemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMayhemServiceHandler struct{}

func (UnimplementedMayhemServiceHandler) ListModels(context.Context, *connect.Request[pb.ListModelsRequest]) (*connect.Response[pb.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mayhem.v1.MayhemService.ListModels is not implemented"))
}

func (UnimplementedMayhemServiceHandler) ChatCompletions(context.Context, *connect.Request[pb.ChatCompletionRequest]) (*connect.Response[pb.ChatCompletionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mayhem.v1.MayhemService.ChatCompletions is not implemented"))
}

func (UnimplementedMayhemServiceHandler) Completions(context.Context, *connect.Request[pb.CompletionRequest]) (*connect.Response[pb.CompletionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mayhem.v1.MayhemService.Completions is not implemented"))
}

func (UnimplementedMayhemServiceHandler) StreamCompletions(context.Context, *connect.Request[pb.CompletionRequest], *connect.ServerStream[pb.StreamChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mayhem.v1.MayhemService.StreamCompletions is not implemented"))
}

func (UnimplementedMayhemServiceHandler) StreamChatCompletions(context.Context, *connect.Request[pb.ChatCompletionRequest], *connect.ServerStream[pb.StreamChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mayhem.v1.MayhemService.StreamChatCompletions is not implemented"))
}

func (UnimplementedMayhemServiceHandler) ListProviders(context.Context, *connect.Request[pb.ListProvidersRequest]) (*connect.Response[pb.ListProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mayhem.v1.MayhemService.ListProviders is not implemented"))
}
