// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: internal/grpc/proto/mayhem.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MayhemService_ListModels_FullMethodName            = "/mayhem.v1.MayhemService/ListModels"
	MayhemService_ChatCompletions_FullMethodName       = "/mayhem.v1.MayhemService/ChatCompletions"
	MayhemService_Completions_FullMethodName           = "/mayhem.v1.MayhemService/Completions"
	MayhemService_StreamCompletions_FullMethodName     = "/mayhem.v1.MayhemService/StreamCompletions"
	MayhemService_StreamChatCompletions_FullMethodName = "/mayhem.v1.MayhemService/StreamChatCompletions"
	MayhemService_ListProviders_FullMethodName         = "/mayhem.v1.MayhemService/ListProviders"
)

// MayhemServiceClient is the client API for MayhemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MayhemService mirrors the OpenAI-compatible gateway surface.
// Go gateway → Rust core via this API.
type MayhemServiceClient interface {
	// ListModels returns all models available from the Rust core.
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// ChatCompletions handles chat-based inference (unary).
	ChatCompletions(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	// Completions handles text completion (unary).
	Completions(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
	// StreamCompletions streams text completion chunks.
	StreamCompletions(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error)
	// StreamChatCompletions streams chat completion chunks.
	StreamChatCompletions(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error)
	// ListProviders returns active providers from the Rust core.
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
}

type mayhemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMayhemServiceClient(cc grpc.ClientConnInterface) MayhemServiceClient {
	return &mayhemServiceClient{cc}
}

func (c *mayhemServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, MayhemService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mayhemServiceClient) ChatCompletions(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, MayhemService_ChatCompletions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mayhemServiceClient) Completions(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, MayhemService_Completions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mayhemServiceClient) StreamCompletions(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MayhemService_ServiceDesc.Streams[0], MayhemService_StreamCompletions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompletionRequest, StreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MayhemService_StreamCompletionsClient = grpc.ServerStreamingClient[StreamChunk]

func (c *mayhemServiceClient) StreamChatCompletions(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MayhemService_ServiceDesc.Streams[1], MayhemService_StreamChatCompletions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, StreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MayhemService_StreamChatCompletionsClient = grpc.ServerStreamingClient[StreamChunk]

func (c *mayhemServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, MayhemService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MayhemServiceServer is the server API for MayhemService service.
// All implementations must embed UnimplementedMayhemServiceServer
// for forward compatibility.
//
// MayhemService mirrors the OpenAI-compatible gateway surface.
// Go gateway → Rust core via this API.
type MayhemServiceServer interface {
	// ListModels returns all models available from the Rust core.
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// ChatCompletions handles chat-based inference (unary).
	ChatCompletions(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	// Completions handles text completion (unary).
	Completions(context.Context, *CompletionRequest) (*CompletionResponse, error)
	// StreamCompletions streams text completion chunks.
	StreamCompletions(*CompletionRequest, grpc.ServerStreamingServer[StreamChunk]) error
	// StreamChatCompletions streams chat completion chunks.
	StreamChatCompletions(*ChatCompletionRequest, grpc.ServerStreamingServer[StreamChunk]) error
	// ListProviders returns active providers from the Rust core.
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	mustEmbedUnimplementedMayhemServiceServer()
}

// UnimplementedMayhemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMayhemServiceServer struct{}

func (UnimplementedMayhemServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedMayhemServiceServer) ChatCompletions(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatCompletions not implemented")
}
func (UnimplementedMayhemServiceServer) Completions(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Completions not implemented")
}
func (UnimplementedMayhemServiceServer) StreamCompletions(*CompletionRequest, grpc.ServerStreamingServer[StreamChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamCompletions not implemented")
}
func (UnimplementedMayhemServiceServer) StreamChatCompletions(*ChatCompletionRequest, grpc.ServerStreamingServer[StreamChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamChatCompletions not implemented")
}
func (UnimplementedMayhemServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedMayhemServiceServer) mustEmbedUnimplementedMayhemServiceServer() {}
func (UnimplementedMayhemServiceServer) testEmbeddedByValue()                       {}

// UnsafeMayhemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MayhemServiceServer will
// result in compilation errors.
type UnsafeMayhemServiceServer interface {
	mustEmbedUnimplementedMayhemServiceServer()
}

func RegisterMayhemServiceServer(s grpc.ServiceRegistrar, srv MayhemServiceServer) {
	// If the following call panics, it indicates UnimplementedMayhemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MayhemService_ServiceDesc, srv)
}

func _MayhemService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MayhemServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MayhemService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MayhemServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MayhemService_ChatCompletions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MayhemServiceServer).ChatCompletions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MayhemService_ChatCompletions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MayhemServiceServer).ChatCompletions(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MayhemService_Completions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MayhemServiceServer).Completions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MayhemService_Completions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MayhemServiceServer).Completions(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MayhemService_StreamCompletions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MayhemServiceServer).StreamCompletions(m, &grpc.GenericServerStream[CompletionRequest, StreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MayhemService_StreamCompletionsServer = grpc.ServerStreamingServer[StreamChunk]

func _MayhemService_StreamChatCompletions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MayhemServiceServer).StreamChatCompletions(m, &grpc.GenericServerStream[ChatCompletionRequest, StreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MayhemService_StreamChatCompletionsServer = grpc.ServerStreamingServer[StreamChunk]

func _MayhemService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MayhemServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MayhemService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MayhemServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MayhemService_ServiceDesc is the grpc.ServiceDesc for MayhemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MayhemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mayhem.v1.MayhemService",
	HandlerType: (*MayhemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _MayhemService_ListModels_Handler,
		},
		{
			MethodName: "ChatCompletions",
			Handler:    _MayhemService_ChatCompletions_Handler,
		},
		{
			MethodName: "Completions",
			Handler:    _MayhemService_Completions_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _MayhemService_ListProviders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCompletions",
			Handler:       _MayhemService_StreamCompletions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamChatCompletions",
			Handler:       _MayhemService_StreamChatCompletions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/grpc/proto/mayhem.proto",
}
