// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: internal/grpc/proto/mayhem.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{0}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{1}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created       int64                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	OwnedBy       string                 `protobuf:"bytes,3,opt,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{3}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Model) GetOwnedBy() string {
	if x != nil {
		return x.OwnedBy
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChatCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Stream        bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{5}
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type ChatChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChoice) Reset() {
	*x = ChatChoice{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChoice) ProtoMessage() {}

func (x *ChatChoice) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChoice.ProtoReflect.Descriptor instead.
func (*ChatChoice) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{6}
}

func (x *ChatChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatChoice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ChatCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created       int64                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*ChatChoice          `protobuf:"bytes,4,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{7}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetChoices() []*ChatChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type CompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Stream        bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{8}
}

func (x *CompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type CompletionChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionChoice) Reset() {
	*x = CompletionChoice{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionChoice) ProtoMessage() {}

func (x *CompletionChoice) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionChoice.ProtoReflect.Descriptor instead.
func (*CompletionChoice) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{9}
}

func (x *CompletionChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CompletionChoice) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CompletionChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type CompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created       int64                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*CompletionChoice    `protobuf:"bytes,4,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{10}
}

func (x *CompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *CompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionResponse) GetChoices() []*CompletionChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *CompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ChoiceDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChoiceDelta) Reset() {
	*x = ChoiceDelta{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChoiceDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceDelta) ProtoMessage() {}

func (x *ChoiceDelta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceDelta.ProtoReflect.Descriptor instead.
func (*ChoiceDelta) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{11}
}

func (x *ChoiceDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Delta         *ChoiceDelta           `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	FinishReason  string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // set on final chunk only
	Usage         *Usage                 `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`                                   // set on final chunk only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{12}
}

func (x *StreamChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamChunk) GetDelta() *ChoiceDelta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *StreamChunk) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *StreamChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{13}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{14}
}

func (x *ListProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`           // "healthy" | "degraded" | "unhealthy"
	Reputation    float64                `protobuf:"fixed64,4,opt,name=reputation,proto3" json:"reputation,omitempty"` // 0.0 – 1.0
	Models        []string               `protobuf:"bytes,5,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_mayhem_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_mayhem_proto_rawDescGZIP(), []int{15}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Provider) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Provider) GetReputation() float64 {
	if x != nil {
		return x.Reputation
	}
	return 0
}

func (x *Provider) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_internal_grpc_proto_mayhem_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_mayhem_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/mayhem.proto\x12\tmayhem.v1\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\x13\n" +
	"\x11ListModelsRequest\">\n" +
	"\x12ListModelsResponse\x12(\n" +
	"\x06models\x18\x01 \x03(\v2\x10.mayhem.v1.ModelR\x06models\"L\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x03R\acreated\x12\x19\n" +
	"\bowned_by\x18\x03 \x01(\tR\aownedBy\"O\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xba\x01\n" +
	"\x15ChatCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x122\n" +
	"\bmessages\x18\x02 \x03(\v2\x16.mayhem.v1.ChatMessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\"y\n" +
	"\n" +
	"ChatChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x120\n" +
	"\amessage\x18\x02 \x01(\v2\x16.mayhem.v1.ChatMessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\xb1\x01\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12/\n" +
	"\achoices\x18\x04 \x03(\v2\x15.mayhem.v1.ChatChoiceR\achoices\x12&\n" +
	"\x05usage\x18\x05 \x01(\v2\x10.mayhem.v1.UsageR\x05usage\"\x9a\x01\n" +
	"\x11CompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\"a\n" +
	"\x10CompletionChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\xb3\x01\n" +
	"\x12CompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x125\n" +
	"\achoices\x18\x04 \x03(\v2\x1b.mayhem.v1.CompletionChoiceR\achoices\x12&\n" +
	"\x05usage\x18\x05 \x01(\v2\x10.mayhem.v1.UsageR\x05usage\"'\n" +
	"\vChoiceDelta\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xae\x01\n" +
	"\vStreamChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12,\n" +
	"\x05delta\x18\x03 \x01(\v2\x16.mayhem.v1.ChoiceDeltaR\x05delta\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\x12&\n" +
	"\x05usage\x18\x05 \x01(\v2\x10.mayhem.v1.UsageR\x05usage\"\x16\n" +
	"\x14ListProvidersRequest\"J\n" +
	"\x15ListProvidersResponse\x121\n" +
	"\tproviders\x18\x01 \x03(\v2\x13.mayhem.v1.ProviderR\tproviders\"\x86\x01\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"reputation\x18\x04 \x01(\x01R\n" +
	"reputation\x12\x16\n" +
	"\x06models\x18\x05 \x03(\tR\x06models2\xf4\x03\n" +
	"\rMayhemService\x12I\n" +
	"\n" +
	"ListModels\x12\x1c.mayhem.v1.ListModelsRequest\x1a\x1d.mayhem.v1.ListModelsResponse\x12V\n" +
	"\x0fChatCompletions\x12 .mayhem.v1.ChatCompletionRequest\x1a!.mayhem.v1.ChatCompletionResponse\x12J\n" +
	"\vCompletions\x12\x1c.mayhem.v1.CompletionRequest\x1a\x1d.mayhem.v1.CompletionResponse\x12K\n" +
	"\x11StreamCompletions\x12\x1c.mayhem.v1.CompletionRequest\x1a\x16.mayhem.v1.StreamChunk0\x01\x12S\n" +
	"\x15StreamChatCompletions\x12 .mayhem.v1.ChatCompletionRequest\x1a\x16.mayhem.v1.StreamChunk0\x01\x12R\n" +
	"\rListProviders\x12\x1f.mayhem.v1.ListProvidersRequest\x1a .mayhem.v1.ListProvidersResponseB)Z'github.com/hivemachine/internal/grpc/pbb\x06proto3"

var (
	file_internal_grpc_proto_mayhem_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_mayhem_proto_rawDescData []byte
)

func file_internal_grpc_proto_mayhem_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_mayhem_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_mayhem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_mayhem_proto_rawDesc), len(file_internal_grpc_proto_mayhem_proto_rawDesc)))
	})
	return file_internal_grpc_proto_mayhem_proto_rawDescData
}

var file_internal_grpc_proto_mayhem_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_grpc_proto_mayhem_proto_goTypes = []any{
	(*Usage)(nil),                  // 0: mayhem.v1.Usage
	(*ListModelsRequest)(nil),      // 1: mayhem.v1.ListModelsRequest
	(*ListModelsResponse)(nil),     // 2: mayhem.v1.ListModelsResponse
	(*Model)(nil),                  // 3: mayhem.v1.Model
	(*ChatMessage)(nil),            // 4: mayhem.v1.ChatMessage
	(*ChatCompletionRequest)(nil),  // 5: mayhem.v1.ChatCompletionRequest
	(*ChatChoice)(nil),             // 6: mayhem.v1.ChatChoice
	(*ChatCompletionResponse)(nil), // 7: mayhem.v1.ChatCompletionResponse
	(*CompletionRequest)(nil),      // 8: mayhem.v1.CompletionRequest
	(*CompletionChoice)(nil),       // 9: mayhem.v1.CompletionChoice
	(*CompletionResponse)(nil),     // 10: mayhem.v1.CompletionResponse
	(*ChoiceDelta)(nil),            // 11: mayhem.v1.ChoiceDelta
	(*StreamChunk)(nil),            // 12: mayhem.v1.StreamChunk
	(*ListProvidersRequest)(nil),   // 13: mayhem.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),  // 14: mayhem.v1.ListProvidersResponse
	(*Provider)(nil),               // 15: mayhem.v1.Provider
}
var file_internal_grpc_proto_mayhem_proto_depIdxs = []int32{
	3,  // 0: mayhem.v1.ListModelsResponse.models:type_name -> mayhem.v1.Model
	4,  // 1: mayhem.v1.ChatCompletionRequest.messages:type_name -> mayhem.v1.ChatMessage
	4,  // 2: mayhem.v1.ChatChoice.message:type_name -> mayhem.v1.ChatMessage
	6,  // 3: mayhem.v1.ChatCompletionResponse.choices:type_name -> mayhem.v1.ChatChoice
	0,  // 4: mayhem.v1.ChatCompletionResponse.usage:type_name -> mayhem.v1.Usage
	9,  // 5: mayhem.v1.CompletionResponse.choices:type_name -> mayhem.v1.CompletionChoice
	0,  // 6: mayhem.v1.CompletionResponse.usage:type_name -> mayhem.v1.Usage
	11, // 7: mayhem.v1.StreamChunk.delta:type_name -> mayhem.v1.ChoiceDelta
	0,  // 8: mayhem.v1.StreamChunk.usage:type_name -> mayhem.v1.Usage
	15, // 9: mayhem.v1.ListProvidersResponse.providers:type_name -> mayhem.v1.Provider
	1,  // 10: mayhem.v1.MayhemService.ListModels:input_type -> mayhem.v1.ListModelsRequest
	5,  // 11: mayhem.v1.MayhemService.ChatCompletions:input_type -> mayhem.v1.ChatCompletionRequest
	8,  // 12: mayhem.v1.MayhemService.Completions:input_type -> mayhem.v1.CompletionRequest
	8,  // 13: mayhem.v1.MayhemService.StreamCompletions:input_type -> mayhem.v1.CompletionRequest
	5,  // 14: mayhem.v1.MayhemService.StreamChatCompletions:input_type -> mayhem.v1.ChatCompletionRequest
	13, // 15: mayhem.v1.MayhemService.ListProviders:input_type -> mayhem.v1.ListProvidersRequest
	2,  // 16: mayhem.v1.MayhemService.ListModels:output_type -> mayhem.v1.ListModelsResponse
	7,  // 17: mayhem.v1.MayhemService.ChatCompletions:output_type -> mayhem.v1.ChatCompletionResponse
	10, // 18: mayhem.v1.MayhemService.Completions:output_type -> mayhem.v1.CompletionResponse
	12, // 19: mayhem.v1.MayhemService.StreamCompletions:output_type -> mayhem.v1.StreamChunk
	12, // 20: mayhem.v1.MayhemService.StreamChatCompletions:output_type -> mayhem.v1.StreamChunk
	14, // 21: mayhem.v1.MayhemService.ListProviders:output_type -> mayhem.v1.ListProvidersResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_mayhem_proto_init() }
func file_internal_grpc_proto_mayhem_proto_init() {
	if File_internal_grpc_proto_mayhem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_mayhem_proto_rawDesc), len(file_internal_grpc_proto_mayhem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_mayhem_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_mayhem_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_mayhem_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_mayhem_proto = out.File
	file_internal_grpc_proto_mayhem_proto_goTypes = nil
	file_internal_grpc_proto_mayhem_proto_depIdxs = nil
}
